# Generated by Django 3.1.3 on 2020-11-17 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contents',
            new_name='Content',
        ),
    ]
