# Generated by Django 3.1.3 on 2020-11-20 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0003_comment_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
