# Generated by Django 3.1.3 on 2020-11-22 07:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0007_auto_20201122_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 22, 7, 58, 9, 792379, tzinfo=utc)),
        ),
    ]
