# Generated by Django 3.1.3 on 2020-11-22 10:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0010_content_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
