# Generated by Django 3.1.3 on 2020-11-22 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0011_auto_20201122_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
