# Generated by Django 3.1.3 on 2020-11-22 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0012_auto_20201122_1957'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['-date']},
        ),
    ]
