# Generated by Django 3.1.3 on 2020-11-22 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0013_auto_20201122_2058'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date']},
        ),
    ]
