# Generated by Django 3.1.3 on 2020-11-25 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0015_recomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recomment',
            name='post',
        ),
    ]
