# Generated by Django 3.1.3 on 2020-11-26 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0018_content_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='like_posts',
            new_name='like_contents',
        ),
    ]
