# Generated by Django 3.1.3 on 2020-11-26 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0022_profile_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_name',
        ),
    ]
