# Generated by Django 3.1.3 on 2020-11-27 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0025_auto_20201127_2345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='profile',
        ),
        migrations.AlterField(
            model_name='content',
            name='writer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='siteapp.profile'),
        ),
    ]
