# Generated by Django 3.1.3 on 2020-11-27 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0026_auto_20201127_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='writer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='siteapp.profile'),
        ),
        migrations.AlterField(
            model_name='recomment',
            name='writer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='siteapp.profile'),
        ),
    ]
