# Generated by Django 3.1.3 on 2020-11-27 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0028_auto_20201128_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siteapp.profile'),
        ),
    ]
