# Generated by Django 3.1.3 on 2020-11-27 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0029_content_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='siteapp.profile'),
        ),
    ]
