# Generated by Django 3.1.3 on 2020-11-27 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0032_board_contents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='contents',
        ),
    ]
