# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    # number of worker nodes
    N = 3
  
    # k8s master
    config.vm.define "m-k8s" do |cfg|
      cfg.vm.box = "ubuntu/focal64"
      cfg.vm.provider "virtualbox" do |vb|
        vb.name = "m-k8s-vm"
        vb.cpus = 2
        vb.memory = 2048
        vb.customize ["modifyvm", :id, "--groups", "/k8s-SM"]
      end 
      cfg.vm.host_name = "m-k8s"
      cfg.vm.network "private_network", ip: "192.168.1.10"
      cfg.vm.network "forwarded_port", guest: 22, host: 60010, auto_correct: true, id: "ssh"
      cfg.vm.synced_folder "./data", "/vagrant"
      cfg.vm.provision "shell", path: "./common.sh"
      cfg.vm.provision "shell", path: "./master.sh"
    end
  
    # Add nodes
  
    # k8s workers
    (1..N).each do |i|
      config.vm.define "w#{i}-k8s" do |cfg|
        cfg.vm.box = "ubuntu/focal64"
        cfg.vm.provider "virtualbox" do |vb|
          vb.name = "w#{i}-k8s-vm"
          vb.cpus = 2
          vb.memory = 1024
          vb.customize ["modifyvm", :id, "--groups", "/k8s-SM"]
        end 
        cfg.vm.host_name = "w#{i}-k8s"
        cfg.vm.network "private_network", ip: "192.168.1.10#{i}"
        cfg.vm.network "forwarded_port", guest: 22, host: "6010#{i}", auto_correct: true, id: "ssh"
        cfg.vm.synced_folder "./data", "/vagrant"
        cfg.vm.provision "shell", path: "./common.sh"
        cfg.vm.provision "shell", path: "./worker.sh"
      end
    end 
  end 
  